model: groq:llama-3.2-90b-vision-preview
save: true
keybinding: vi
wrap_code: true
save_session: false
highlight: true
temperature: 0.8
top_p: 0.95

clients:
  - type: openai-compatible
    name: groq
    api_base: https://api.groq.com/openai/v1
  - type: openai-compatible
    name: openrouter
    api_base: https://openrouter.ai/api/v1
    models:
      - name: anthropic/claude-3-5-haiku
      - name: anthropic/claude-3.5-sonnet
  - type: openai
  - type: openai-compatible
    name: litellm
    api_base: http://localhost:4000
    models:
      - name: gpt-4o
        max_input_tokens: 128000
        supports_vision: true
        supports_function_calling: true
