model: groq:llama-3.1-70b-versatile
save: true
keybinding: vi
wrap_code: true
save_session: true
highlight: true

clients:
  - type: openai-compatible
    name: groq
    api_base: https://api.groq.com/openai/v1
  - type: openai
    api_base: https://api.openai.com/v1
  - type: claude
