model: groq:llama-3.2-90b-text-preview
save: true
keybinding: vi
wrap_code: true
save_session: true
highlight: true
temperature: 0.8
top_p: 0.95

clients:
  - type: openai-compatible
    name: groq
    api_base: https://api.groq.com/openai/v1
  - type: openai
    api_base: https://api.openai.com/v1
  - type: claude
