format = """
$username\
$hostname\
$directory\
$python\
$git_branch\
$git_state\
$git_metrics\
$git_status\
$line_break\
$character\
"""

right_format = """
$cmd_duration\
$status\
"""

[git_metrics]
disabled = false
