[qt]
GUIEffects=none
KDE\contrast=4
KWinPalette\activeBackground=#ffffff
KWinPalette\activeBlend=#565656
KWinPalette\activeForeground=#424242
KWinPalette\activeTitleBtnBg=#ffffff
KWinPalette\frame=#ffffff
KWinPalette\inactiveBackground=#f5f5f5
KWinPalette\inactiveBlend=#666666
KWinPalette\inactiveForeground=#787878
KWinPalette\inactiveFrame=#ffffff
KWinPalette\inactiveTitleBtnBg=#ffffff
Palette\active=#242424, #ffffff, #e6e6e6, #f3f3f3, #d9d9d9, #e6e6e6, #242424, #ffffff, #242424, #ffffff, #ffffff, #c1c1c1, #899fca, #000000, #3f5783, #7f8c8d, #efefef, #000000, #242424, #dedede, #787878, #899fca
Palette\disabled=#aaaaaa, #f3f3f3, #ffffff, #fafafa, #8f8f8f, #cacaca, #aaaaaa, #ffffff, #aaaaaa, #f3f3f3, #f3f3f3, #494949, #f3f3f3, #aaaaaa, #b1bbcd, #c8cdcd, #e4e4e4, #000000, #242424, #dedede, #c6c6c6, #f3f3f3
Palette\inactive=#242424, #ffffff, #e6e6e6, #f3f3f3, #d9d9d9, #e6e6e6, #242424, #ffffff, #242424, #ffffff, #ffffff, #c1c1c1, #e2e7f1, #242424, #3f5783, #7f8c8d, #efefef, #000000, #242424, #dedede, #787878, #e2e7f1
font="SF Pro Display,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
