return {
	"williamboman/mason.nvim",
	dependencies = { "williamboman/mason-lspconfig.nvim" },
	config = function()
		require("mason").setup()
		require("mason-lspconfig").setup({
			ensure_installed = {
				"astro",
				"bashls",
				"biome",
				"cssls",
				-- "dartls",
				"docker_compose_language_service",
				"dockerls",
				"emmet_ls",
				"eslint",
				"gopls",
				"html",
				"lua_ls",
				"pyright",
				"rust_analyzer",
				"sqlls",
				"stylelint_lsp",
				"svelte",
				"tailwindcss",
				"ts_ls",
				"yamlls",
				-- "prettier_d",
				-- "eslint_d",
				-- "stylua",
				-- "goimports",
				-- "gofumpt",
				-- "sql-formatter",
				-- "sqlfluff",
				-- "yapf",
				-- "shfmt",
			},
		})
	end,
}
